### PR TITLE
Fix Issue #640 Gradle resource dir not set properly

### LINKED ISSUE #640: Gradle resourceDir not set properly
When using gradle project type resourceDir is set to classOutputDir thus application properties are not applied

### PR DESCRIPTION
**Pull request by dswiecki**
Resolves #640

### CODE REVIEW

File: core/src/main/java/io/dekorate/project/BuildInfo.java [hunk 1]
```diff
@@ -37,22 +37,6 @@ public BuildInfo() {
     this(null, null, DEFAULT_PACKAGING, DEFAULT_BUILD_TOOL, null, null, null, null);
   }
 
-  /**
```
Comment (iocanel) [inline core/src/main/java/io/dekorate/project/BuildInfo.java:40]: This might be used by downstream projects, so I'd like to bring this back.

**Review by iocanel — CHANGES_REQUESTED** [review]
Overall, it looks good. 

The only thing I'd like to change is to bring back the constructor that got deleted.

**Review by iocanel — APPROVED** [review]
I went on to add the method back, then I felt it might be better this way as in the long run it might cause more issues than it will solve.

So, I'll accept it as is.
